[Icon Theme]
Name=Kali-Dragon-Icons-Magenta
Comment=Kali Dragon Cyberpunk Neon Wireframe Icon Suite (Magenta Edition)
Inherits=Flat-Remix-Pink-Dark,Flat-Remix-Blue-Dark,Papirus-Dark,Adwaita,hicolor
Directories=scalable/places,scalable/devices,scalable/apps,scalable/actions,scalable/mimetypes,scalable/status,symbolic/places,symbolic/actions,symbolic/devices,symbolic/status

[scalable/places]
Size=64
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Size=64
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512

[scalable/apps]
Size=64
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[scalable/actions]
Size=64
Context=Actions
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Size=64
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Size=64
Context=Status
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/places]
Size=16
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/actions]
Size=16
Context=Actions
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/devices]
Size=16
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/status]
Size=16
Context=Status
Type=Scalable
MinSize=16
MaxSize=512
