[greeter]
background = /usr/share/desktop-base/kali-theme/login/login-background.png
theme-name = Kali-Indigo-Dragon-Login
icon-theme-name = Flat-Remix-Blue-Dark
font-name = Cantarell 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = slight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %a %d %b, %H:%M
user-background = false
default-user-image = /usr/share/desktop-base/kali-theme/login/dragon-avatar.png
hide-user-image = false
