[greeter]
background = /usr/share/desktop-base/kali-theme/login/login-background.png
theme-name = Kali-Orange-Dragon-Login
icon-theme-name = Flat-Remix-Orange-Dark
font-name = Cantarell 11
indicators = ~host;~spacer;~clock;~spacer;~session;~a11y;~power;
clock-format = %A %d de %B  •  %H:%M
default-user-image = /usr/share/desktop-base/kali-theme/login/dragon-avatar.png
round-user-image = true
position = 50%,center 50%,center
